### ISSUE TITLE
Add option to add __typename field automatically for query operations

### ISSUE THREAD

**Issue by tomocrafter** [uhyo/nitrogql#36]
I apologize for creating issues rapidly. If it has been bothersome, please let me know, and I will stop.
The apollo client automatically adds `__typename` field for every query operations to distinguish the value for caching. In order to migrate to nitrogql from graphql-let which supports similar function, we wanted to add option to support it.
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations#skiptypename

**Comment by uhyo** [comment]
No problem! 🙂 Ease of migration is important for nitrogql to be accepted by the community.

Regarding this feature, I'm a bit concerned that automatically adding `__typename` to the result type might be a lie if user doesn't use such a client.

Apollo client should do its job regardless of whether `__typename` is specified in type level, so the issue is about touching `__typename` from application code, if I understand correctly.
Is it an option to manually add `__typename` to GraphQL queries when you need to inspect it from application code? I believe this generally happens when handling union type results.

**Comment by tomocrafter** [comment]
Thank you very much!

As you mentioned, there is a potential for user confusion if such a feature is added when the user is not using that kind of client. In the issue description, I noted that "graphql-let has this feature," but this feature is actually generated by the plugin @graphql-codegen/typescript-react-apollo. As the name suggests, it's a plugin for Apollo Client, and normally, __typename is not automatically generated with it. You can see more about it here: [typescript-react-apollo plugin](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-apollo#skiptypename).

Additionally, Apollo Client adds __typename to the document at runtime, so it doesn't affect the execution if it's not present in the types. If __typename is needed at the type level, it seems reasonable to manually add it. It might be worth considering this after a feature like the one in the plugin is implemented in nitrogql. Therefore, I will go ahead and close this issue for now. Thank you for taking time.
